// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiMO5JH_k7udFOIWvmCEJmr5WkqNCMkZo',
    appId: '1:312868804647:web:1ee5fc52c41a5f2e205602',
    messagingSenderId: '312868804647',
    projectId: 'socialapp-481c7',
    authDomain: 'socialapp-481c7.firebaseapp.com',
    storageBucket: 'socialapp-481c7.appspot.com',
    measurementId: 'G-NZXS58L759',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWc9q-SpOk-Q3mNOovDPd6F0slaErUZBY',
    appId: '1:312868804647:android:99e7cd7d23984776205602',
    messagingSenderId: '312868804647',
    projectId: 'socialapp-481c7',
    storageBucket: 'socialapp-481c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Wk20tI5uUb-Wa4uEgq-rgzI9RVHp00w',
    appId: '1:312868804647:ios:4eaffbed40a236a0205602',
    messagingSenderId: '312868804647',
    projectId: 'socialapp-481c7',
    storageBucket: 'socialapp-481c7.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Wk20tI5uUb-Wa4uEgq-rgzI9RVHp00w',
    appId: '1:312868804647:ios:d9c99199d55716b7205602',
    messagingSenderId: '312868804647',
    projectId: 'socialapp-481c7',
    storageBucket: 'socialapp-481c7.appspot.com',
    iosBundleId: 'com.example.socialapp.RunnerTests',
  );
}
